version: "3"

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - 8080:80
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    environment:
      - NODE_ENV=development
    command: "npm run dev"

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3001:80
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    volumes:
      - db_todo_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret

volumes:
  db_todo_data:
